i=imread('cameraman.tif');
cd=double(i);
%imshow(i)
c=mod(cd,2);
figure,imshow(c)
c1=mod(floor(cd/2),2);
figure,imshow(c1)
c2=mod(floor(cd/4),2);
figure,imshow(c2)
c3=mod(floor(cd/8),2);
figure,imshow(c3)
c4=mod(floor(cd/16),2);
figure,imshow(c4)
c5=mod(floor(cd/32),2);
figure,imshow(c5)
c6=mod(floor(cd/64),2);
figure,imshow(c6)
c7=mod(floor(cd/128),2);
figure,imshow(c7)